### ISSUE TITLE
Move DevX Digests from gitpod.io/blog to developerexperience.us/blog

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/devx-community#97]
See [internal discussion.](https://gitpod.slack.com/archives/C0401SXP0FP/p1662555287722629)

**Comment by pawlean** [comment]
@Cahllagerfeld @chrifro I've created this issue for us to capture thoughts from recent feedback on Slack.

@Cahllagerfeld You said this should be relatively simple! In terms of timeline, could we aim for this to be live in the next 1-2 weeks? It might be a good time to as we are seeing a lot of new members' activities! We could refer back to this to encourage folks to also share their own posts.

**Comment by Cahllagerfeld** [comment]
I can start setting up the infrastructure for the blogpost. Once that's done we can start implementing the layout for the blog and migrate the content

**Comment by chrifro** [comment]
I would say it make more sense to first conceptually explain the change, then create the visual mockup, followed by the technical implementation. 

Some questions I'd have:
- would we delete all DevX Digest blog posts on gitpod.io or will it be a duplicate blog?
- if we delete it, how does it affect gitpod.io? How many page views are we losing? (see Mode report)
- how does it affect the email layout for the devX Digest? Currently, it follows the Gitpod design, should it follow the developerexperience branding instead? 
- How do you envision the implementation on developerexperience? Will there be a simple link under "DevX Blog" or/and should we add a navigation menu with a link to it? Would it then be the only navigation item? 
- Will it be called DevX Blog or DevX Digest?
- How will the community be able to contribute to it? How do we want to distinguish between devX Digest and community contributions?

I didn't know that moving the blog to developerexperience was a discussion item and postponed for the sprint. I think it'd have made more sense to include it from the beginning and to make sure that the website structure fits it. Let's make sure that these decisions are better documented next time so that we can jump in and propose to include it directly or to at least have it in mind when implementing it. :) 

I'd suggest that we put this issue on hold until @pawlean is back from vacation and can resolve the open questions.

**Comment by pawlean** [comment]
I'm back, thanks for the thoughtful questions as usual @chrifro! 

> would we delete all DevX Digest blog posts on gitpod.io or will it be a duplicate blog?
> if we delete it, how does it affect gitpod.io? How many page views are we losing? (see Mode report)

1️⃣ After some thought, I don't think the DevX Digest blog posts on gitpod.io is excessively linked elsewhere... I don't have the exact data, but I believe most people read the digest via the actual newsletter rather than the blog post. So I think it's safe to just remove all blog posts on gitpod.io and migrate them fully to developerexperience.us. 

2️⃣ Or maybe set up redirects from gitpod.io to developerexperience.us.

> how does it affect the email layout for the devX Digest? Currently, it follows the Gitpod design, should it follow the developerexperience branding instead?

Yes, let's start using developerexperience.us branding moving forward for all DevX Digest emails. 

> How do you envision the implementation on developerexperience? Will there be a simple link under "DevX Blog" or/and should we add a navigation menu with a link to it? Would it then be the only navigation item?

I thought that with the current layout it would be easiest to have a simple link under "DevX Blog" that links to `/blog` with all the blog posts (similar to gitpod.io/blog)

> Will it be called DevX Blog or DevX Digest?
> How will the community be able to contribute to it? How do we want to distinguish between devX Digest and community contributions?

DevX digest posts would just be one category of posts. So under **DevX Blog** > **DevX Digest** (category) I also imagine in the future if we hopefully get more contributors writing posts, there could be a **Community posts** category.

Let me know if there's anything in the above that needs more clarity. Also thank you to @jacobparis for syncing with me on the discussion you had in a website sync, it was helpful to get extra context on discussions that have already happened. 🧡

**Comment by MichaelAring** [comment]
Let's keep in mind that we have limited website & design resources and should focus on activities that have the highest impact on our goals.

- Currently, developerexperience.us serves 2 purposes: (1) home/entrance to our community, (2) collection of helpful links to DevX resources
- By creating a new hosted content library on developerexperience.us, we will create additional maintenance effort for the team for a slightly improved user experience
- By removing content from the Gitpod blog, we would reduce traffic on the Gitpod website

I am not in favor of investing engineering and design resources into this, currently. I think the costs to Gitpod outweigh the benefits to the users of developerexperience.us.

**Comment by pawlean** [comment]
As we discussed in a DCS sync, let's close this and maybe revisit for the future. Thanks for your input, @MichaelAring!
